//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9148
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiwin.ERP.X_ITEM_AVG_CONSUMPTION.UI.Implement.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digiwin.ERP.X_ITEM_AVG_CONSUMPTION.UI.Implement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 月均耗用量 的本地化字符串。
        /// </summary>
        internal static string LB_AVG_CONSUMPTION {
            get {
                return ResourceManager.GetString("LB_AVG_CONSUMPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Excel页签[{0}]读取错误。行：[{1}]，列：[{2}]。异常：{3} 的本地化字符串。
        /// </summary>
        internal static string LB_EXCEL_LOAD_ERROR {
            get {
                return ResourceManager.GetString("LB_EXCEL_LOAD_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品号 的本地化字符串。
        /// </summary>
        internal static string LB_ITEM_CODE {
            get {
                return ResourceManager.GetString("LB_ITEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品名 的本地化字符串。
        /// </summary>
        internal static string LB_ITEM_NAME {
            get {
                return ResourceManager.GetString("LB_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 规格 的本地化字符串。
        /// </summary>
        internal static string LB_ITEM_SPEC {
            get {
                return ResourceManager.GetString("LB_ITEM_SPEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页签[{0}]的列同数据列无法匹配。\r\n列:[{1}]\r\n 数据[{2}] 的本地化字符串。
        /// </summary>
        internal static string LB_LOAD_NOT_MATCH {
            get {
                return ResourceManager.GetString("LB_LOAD_NOT_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能为空。 的本地化字符串。
        /// </summary>
        internal static string LB_NOT_EMPTY {
            get {
                return ResourceManager.GetString("LB_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工厂 的本地化字符串。
        /// </summary>
        internal static string LB_PLANT_CODE {
            get {
                return ResourceManager.GetString("LB_PLANT_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缺少关键列 的本地化字符串。
        /// </summary>
        internal static string MSG_COLUMN_MISSING {
            get {
                return ResourceManager.GetString("MSG_COLUMN_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出失败！ 的本地化字符串。
        /// </summary>
        internal static string MSG_EXCEL_ERR {
            get {
                return ResourceManager.GetString("MSG_EXCEL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功! 的本地化字符串。
        /// </summary>
        internal static string MSG_EXCEL_OK {
            get {
                return ResourceManager.GetString("MSG_EXCEL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string MSG_EXPORT {
            get {
                return ResourceManager.GetString("MSG_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消中... 的本地化字符串。
        /// </summary>
        internal static string MSG_EXPORT_CANCELING {
            get {
                return ResourceManager.GetString("MSG_EXPORT_CANCELING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到文件中... 的本地化字符串。
        /// </summary>
        internal static string MSG_EXPORTING {
            get {
                return ResourceManager.GetString("MSG_EXPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Excel 2007(*.xlsx)|*.xlsx|Microsoft Excel 2003(*.xls)|*.xls 的本地化字符串。
        /// </summary>
        internal static string MSG_EXT_EXCEL {
            get {
                return ResourceManager.GetString("MSG_EXT_EXCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string MSG_IMPORT {
            get {
                return ResourceManager.GetString("MSG_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败！ 的本地化字符串。
        /// </summary>
        internal static string MSG_IMPORT_ERR {
            get {
                return ResourceManager.GetString("MSG_IMPORT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入成功！ 的本地化字符串。
        /// </summary>
        internal static string MSG_IMPORT_OK {
            get {
                return ResourceManager.GetString("MSG_IMPORT_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入数据中... 的本地化字符串。
        /// </summary>
        internal static string MSG_IMPORTING {
            get {
                return ResourceManager.GetString("MSG_IMPORTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以下{0}没有成功导入: 的本地化字符串。
        /// </summary>
        internal static string MSG_NOT_IMPORTED {
            get {
                return ResourceManager.GetString("MSG_NOT_IMPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持该文件导入！ 的本地化字符串。
        /// </summary>
        internal static string NotSupportFileType {
            get {
                return ResourceManager.GetString("NotSupportFileType", resourceCulture);
            }
        }
    }
}
