//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4961
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digiwin.ERP.X_PP_B003.Business.Implement.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Digiwin.ERP.X_PP_B003.Business.Implement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 处理中。。。 的本地化字符串。
        /// </summary>
        internal static string LABEL_000001 {
            get {
                return ResourceManager.GetString("LABEL_000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中。。。 的本地化字符串。
        /// </summary>
        internal static string LABEL_000002 {
            get {
                return ResourceManager.GetString("LABEL_000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此规划策略不存在或未生效，不执行MRP计划排程生成！ 的本地化字符串。
        /// </summary>
        internal static string LABEL_000003 {
            get {
                return ResourceManager.GetString("LABEL_000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此规划策略与前端输入的工厂不符，不执行MRP计划排程生成！ 的本地化字符串。
        /// </summary>
        internal static string LABEL_000004 {
            get {
                return ResourceManager.GetString("LABEL_000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此规划策略尚未启动MRP，不执行MRP计划排程生成！ 的本地化字符串。
        /// </summary>
        internal static string LABEL_000005 {
            get {
                return ResourceManager.GetString("LABEL_000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此规划策略是不可重排的状态，不执行MRP计划排程生成！ 的本地化字符串。
        /// </summary>
        internal static string LABEL_000006 {
            get {
                return ResourceManager.GetString("LABEL_000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理中。。。 的本地化字符串。
        /// </summary>
        internal static string LABEL_000007 {
            get {
                return ResourceManager.GetString("LABEL_000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理完成 的本地化字符串。
        /// </summary>
        internal static string LABEL_000008 {
            get {
                return ResourceManager.GetString("LABEL_000008", resourceCulture);
            }
        }
    }
}
